# scratchpad

from utils import *
from model_01 import Model

m = Model()


def test_model():

    pp(m.__dict__)  # model attributes
    pp(dir(m))


    m.create_language_from_ML1()  # generate language from ML1
    m.generate_random_message()  # generate random message
    m.message  # the current message in its raw form
    m.draw_message()  # draw message as a tree (the same current message visualized as a tree)
    m.message_structure  # setting of the branching structure of the message generated by the model
    m.lexicalize_message()
    m.sentence_set
